name: Build Paper
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper-server/build/libs/paper-paperclip-*-mojmap.jar
